
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: mark_development
    # adapter: sqlite3 # Override default for development
    # database: db/development.sqlite3
  queue:
    <<: *default
    database: mark_development_queue
    # adapter: sqlite3 # Override default for development
    # database: db/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: mark_development_cable
    # adapter: sqlite3 # Override default for development
    # database: db/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: mark_test
    # adapter: sqlite3 # Override default for development
    # database: db/test.sqlite3
  queue:
    <<: *default
    database: mark_test_queue
    # adapter: sqlite3 # Override default for development
    # database: db/test_queue.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: mark_production_cache
    url: <%= ENV["CACHE_DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mark_production_queue
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
    pool: 25
  cable:
    <<: *primary_production
    database: mark_production_cable
    url: <%= ENV["CABLE_DATABASE_URL"] %>
    migrations_paths: db/cable_migrate